### ISSUE TITLE
Matplotlib + Pandas errors

### ISSUE THREAD

**Issue by pdunstan88776** [Hive-Systems/pyfair#59]
Getting the following, any suggestions?

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py:257: FutureWarning: The provided callable <function mean at 0x104970b80> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  risk_results = risk_results.agg([np.mean, np.std, np.min, np.max])
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py:257: FutureWarning: The provided callable <function std at 0x104970cc0> is currently using Series.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  risk_results = risk_results.agg([np.mean, np.std, np.min, np.max])
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py:257: FutureWarning: The provided callable <function min at 0x1049702c0> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  risk_results = risk_results.agg([np.mean, np.std, np.min, np.max])
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py:257: FutureWarning: The provided callable <function max at 0x104970180> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  risk_results = risk_results.agg([np.mean, np.std, np.min, np.max])
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py:260: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  overview_df = risk_results.applymap(lambda x: self._format_strings['Risk'].format(x))
Traceback (most recent call last):
  File "/Users/seq/test.py", line 22, in <module>
    fsr.to_html('output.html')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py", line 164, in to_html
    output = self._construct_output()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/simple_report.py", line 57, in _construct_output
    hist = self._get_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/base_report.py", line 220, in _get_distribution
    fig, ax = fdc.generate_image()
              ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfair/report/distribution.py", line 107, in generate_image
    tick.label.set_horizontalalignment('left')
    ^^^^^^^^^^
AttributeError: 'XTick' object has no attribute 'label'. Did you mean: '_label'?

**Comment by pdunstan88776** [comment]
I seem to have resolved errors and got this working, multiple patches applied to code:

**distribution.py & excellence.py:**
Update all references from 'label' on XTick object to 'label1'
(ref: https://stackoverflow.com/questions/48194542/align-specific-x-labels-differently-to-each-other)

**base_report.py**
Update all references from 'applymap' to 'map'

*tree_graph.py**
Update all references from 'iteritems()' to 'items()'
(ref: https://stackoverflow.com/questions/76200452/error-while-iterating-over-dataframe-columns-entries-attributeerror-series)

**Comment by deved99** [comment]
Hi! I see the errors mentioned in the first post when I try the latest release with the example code in the readme. Since the last release is from September 2020, I guess this patch isn't included when I install this library with:
```
pip install pyfair
```
Is it correct? How can I install the updated library?
